logoText = "Opinionator" # Logo text that appears in the site navigation bar.
description = "A blog about various computer science and software engineering related topics." # for SEO
custom_css = ["css/font.css", "scss/custom.scss"] # custom_css = ["scss/custom.scss"] and then make file at root/assets/scss/custom.scss
custom_js = [] # custom_js = ["js/custom.js"] and then make file at root/assets/js/custom.js

# header
homeHeaderType = "text" # text, img, slide

# navbar
enableThemeChange = false # site color theme

# body
# enableBreadcrumb = false # breadcrumb for list, single page
# enablePhotoSwipe = true # image viewer for gallery, single page
# enableSearch = true # site search with Fuse
# enableSearchHighlight = true # when true, search keyword will be highlighted
enableGoToTop = true # scroll to top
enableWhoami = true # at the end of single page
summaryShape = "classic" # card, classic, compact
archiveGroupByDate = "2006" # "2006-01": group by month, "2006": group by year
archivePaginate = 1000 # items per page
paginateWindow = 1 # setting it to 1 gives 7 buttons, 2 gives 9, etc. If set 1: [1 ... 4 5 6 ... 356] [1 2 3 4 5 ... 356] etc

# whoami: usage - home page sidebar, single page bottom of post. all values can be empty
myname = "Sean Carpenter"
email = "seancarpenter10@gmail.com"
whoami = "Software Engineer"
useGravatar = false
location = "Washington D.C."
# organization = "Hugo"
link = "https://github.com/seancarpenter"

# sidebar
enableBio = true # home page sidebar
enableSidebar = true # Set to false to create the full width of the content.
# enableSidebarTags = true # if you want to use tags.
# enableSidebarSeries = true
# enableSidebarCategories = true
enableToc = false # single page table of contents, you can replace this param to toc(toc = true)
hideToc = false # Hide or Show toc
enableTocSwitch = true # single page table of contents visibility switch
itemsPerCategory = 5 # maximum number of posts shown in the sidebar.

# footer
showPoweredBy = true # show footer text: Powered by Hugo and Zzo theme
showFeedLinks = true # RSS Feed
showSocialLinks = true # email, facebook, twitter ...
# enableLangChange = true # show button at bottom left of footer.
themeOptions = ["dark", "light", "hacker", "solarized", "custom"] # select options for site color theme

# comment
enableComment = false
disqus_shortname = ""
commento = false

[socialOptions] # if set, social icons will show up.
  email = "mailto:seancarpenter10@gmail"
  facebook = ""
  twitter = ""
  github = "https://www.github.com/seancarpenter"
  stack-overflow = ""
  instagram = ""
  youtube = ""
  medium = ""
  tumblr = ""
  linkedin = ""
  stack-exchange = ""
  steam = ""
  gitlab = ""
  mastodon = ""

[donationOptions]
  enable = false # if set, the donation button will show up on the single page.
  paypal = "" # Paypal URL
  patreon = "" # Patreon URL

[copyrightOptions]
  enableCopyrightLink = false # if set, you can add copyright link
  copyrightLink = ""
  copyrightLinkImage = ""
  copyrightLinkText = ""
